version: '3'
services:
  hyperf-skeleton:
    container_name: hyperf-skeleton
#    image: hyperf/hyperf:8.1-alpine-v3.18-swoole
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

  hyperf-db:
    container_name: hyperf-db
    image: mysql:8.1
#    command: --default-authentication-plugin=mysql_native_password
    volumes:
#      - ./.docker/mariadb:/var/lib/mysql
      - ./.docker/mariadb:/docker-entrypoint-initdb.d/migrations.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  hyperf-skeleton-redis:
    container_name: hyperf-skeleton-redis
    image: redis:latest
    ports:
      - 6379:6379

networks:
  default:
    name: hyperf-skeleton
